EPAM.Library.PL.WebPL/Controllers/BookController.cs
using AutoMapper;
using EPAM.Library.BLL.Interfaces;
using EPAM.Library.Common;
using EPAM.Library.Entities;
using EPAM.Library.PL.WebPL.ViewModels.Book;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EPAM.Library.PL.WebPL.Controllers
{
    public class BookController : Controller
    {
        private IBookLogic bookLogic = BookDependencyResolver.BookLogic;

        // GET: BookController
        public ActionResult Index()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Book, DisplayBookVM>());
            IMapper mapper = new Mapper(config);

            var books = mapper.Map<IEnumerable<DisplayBookVM>>(bookLogic.GetAll());
            return View(books);
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] CreateBookVM bookVM)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var config = new MapperConfiguration(cfg => cfg.CreateMap<CreateBookVM, Book>());
            IMapper mapper = new Mapper(config);

            //try
            //{
                var book = mapper.Map<Book>(bookVM);
                bookLogic.Add(book);
            //}
            //catch
            //{

            //}

            
            
            try 
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

EPAM.Library.PL.WebPL/Controllers/NewspaperController.cs
using AutoMapper;
using EPAM.Library.BLL.Interfaces;
using EPAM.Library.Common;
using EPAM.Library.Entities;
using EPAM.Library.PL.WebPL.Models.Newspaper;
using Microsoft.AspNetCore.Mvc;

namespace EPAM.Library.PL.WebPL.Controllers
{
    public class NewspaperController : Controller
    {
        private INewspaperLogic _newspaperLogic;
        public NewspaperController()
        {
           _newspaperLogic = NewspaperDependencyResolver.NewspaperLogic;
        }
         
        public IActionResult Index()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Newspaper, DisplayNewspaperVM>());
            IMapper mapper = new Mapper(config);

            var newspapers = mapper.Map<IEnumerable<DisplayNewspaperVM>>(_newspaperLogic.GetAll());
            return View(newspapers);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] CreateNewspaperVM bookVM)
        {
            if(bookVM.IssueDate.Year != bookVM.PublicationYear)
            {
                ModelState.AddModelError("IssueDate", "Wrong date: year of publishing is not the same as year of issue");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }
            
            var config = new MapperConfiguration(cfg => cfg.CreateMap<CreateNewspaperVM, Newspaper>());

            IMapper mapper = new Mapper(config);
            var book = mapper.Map<Newspaper>(bookVM);

            _newspaperLogic.Add(book);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

EPAM.Library.PL.WebPL/Controllers/PatentController.cs
using AutoMapper;
using EPAM.Library.BLL.Interfaces;
using EPAM.Library.Common;
using EPAM.Library.Entities;
using EPAM.Library.PL.WebPL.Models.Patents;
using Microsoft.AspNetCore.Mvc;

namespace EPAM.Library.PL.WebPL.Controllers
{
    public class PatentController : Controller
    {
        IPatentLogic _patentLogic;
        public PatentController()
        {
            _patentLogic = PatentDependencyResolver.PatentLogic;
        }

        public IActionResult Index()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Patent, DisplayPatentVM>());

            IMapper mapper = new Mapper(config);
            var patents = mapper.Map<IEnumerable<DisplayPatentVM>>(_patentLogic.GetAll());

            return View(patents);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePatentVM patentVM)
        {
            if(patentVM.ApplicationDate > patentVM.PublicationDate)
            {
                ModelState.AddModelError("ApplicationDate", "Application date cannot be later than the publication date");
            }
            
            if (!ModelState.IsValid)
            {
                return View();
            }

            var config = new MapperConfiguration(cfg => cfg.CreateMap<CreatePatentVM, Patent>());

            IMapper mapper = new Mapper(config);
            var patent = mapper.Map<Patent>(patentVM);

            _patentLogic.Add(patent);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        } 
    }
}

EPAM.Library.PL.WebPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswathTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EPAM.Library.PL.WebPL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" asp-controller="Book" asp-action="Index">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Newspaper" asp-action="Index">Newspapers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Patent" asp-action="Index">Patents</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top blockquote-footer text-muted">
        <div class="container">
            &copy; 2022 - Library - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>